### PR TITLE
Add pretty rendering options

### PR DESCRIPTION
**Pull request by tshort**
This is for #4.

This PR adds another type of context for holding state during rendering. This includes a flag for pretty printing as well as the indentation level.

The algorithm for pretty printing is pretty simple. Every node is printed on a line by itself. If a node has non-plain content, then the leading and trailing tags are put on their own line. You can get pretty crazy with pretty printing, but this is easy to implement and not bad visually. For CSS, I only added a newline for each heading.

I left the defaults without pretty rendering, mainly so tests would work. It's possible to have different defaults for `show` than for `render`.

Here is an example:

```julia
julia> using Hyperscript

julia> @tags html head body div span form label input select option strong pre table tbody tr td h1 h2

julia> @tags_noescape style

julia> h = html(head(style(css(".entry",
                               fontSize="14px",
                               css("h1", textDecoration="underline"),
                               css("> p", color="#999")))),
                body(h1("My heading"),
                     div("This is a div:", strong("hi!")),
                     div(div(div("Some more text"))),
                     table(tbody(tr(td(1), td(2)), tr(td(3), td(4))))))
<html><head><style>.entry {font-size: 14px;}.entry h1 {text-decoration: underline;}.entry > p {color: #999;}</style></head><body><h1>My heading</h1><div>This is a div:<strong>hi&#33;</strong></div><div><div><div>Some more text</div></div></div><table><tbody><tr><td>1</td><td>2</td></tr><tr><td>3</td><td>4</td></tr></tbody></table></body></html>

julia> print(render(h, prettyprint = true))

<html>
  <head>
    <style>
      .entry {font-size: 14px;}
      .entry h1 {text-decoration: underline;}
      .entry > p {color: #999;}
    </style>
  </head>
  <body>
    <h1>My heading</h1>
    <div>This is a div:
      <strong>hi&#33;</strong>
    </div>
    <div>
      <div>
        <div>Some more text</div>
      </div>
    </div>
    <table>
      <tbody>
        <tr>
          <td>1</td>
          <td>2</td>
        </tr>
        <tr>
          <td>3</td>
          <td>4</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>

julia> print(render(h, prettyprint = true, indent = ""))

<html>
<head>
<style>
.entry {font-size: 14px;}
.entry h1 {text-decoration: underline;}
.entry > p {color: #999;}
</style>
</head>
<body>
<h1>My heading</h1>
<div>This is a div:
<strong>hi&#33;</strong>
</div>
<div>
<div>
<div>Some more text</div>
</div>
</div>
<table>
<tbody>
<tr>
<td>1</td>
<td>2</td>
</tr>
<tr>
<td>3</td>
<td>4</td>
</tr>
</tbody>
</table>
</body>
</html>

```

### CODE REVIEW

**Comment by yurivish** [comment]
Thank you — this is great! 

I'll have a closer look soon, but I did notice that the first node prints with a prepended newline before the first element. Do you see a simple way to prevent that? Playing with the code I didn't see one, since that newline is important for things to nest properly.

**Comment by tshort** [comment]
The latest commit removes the first newline.

**Comment by yurivish** [comment]
Doh. 'Twas late last night; I missed doing it that way. :-)

**Comment by yurivish** [comment]
> I left the defaults without pretty rendering, mainly so tests would work. 

One subtlety here is that code can be whitespace-sensitive, e.g. if certain CSS properties are used, such as [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).

**Pull request merged**
